services:

  # Fastapi app
  fastapi:
    build:
      context: ..
      dockerfile: docker/minirag/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.app
    restart: always
    volumes:
      - fastapi_data:/app/assets
    networks:
      - backend

  # Nginx reverse proxy
  # nginx:
  #   image: nginx:stable-alpine3.23-perl
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - fastapi
  #   restart: always
  #   networks:
  #     - backend

  # # Postgres database (pgvector)
  # pgvector:
  #   image: pgvector/pgvector:0.8.1-pg18-trixie
  #   container_name: pgvector
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgvector_data:/var/lib/postgresql
  #   env_file:
  #     - ./env/.env.postgres
  #   restart: always
  #   networks:
  #     - backend
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s

  # # Qdrant vector database
  # qdrant:
  #   image: qdrant/qdrant:v1.17
  #   container_name: qdrant
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   volumes:
  #     - qdrant_data:/qdrant/storage
  #   restart: always
  #   networks:
  #     - backend

  # # Prometheus monitoring
  # prometheus:
  #   image: prom/prometheus:v3.5.1
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - prometheus_data:/prometheus
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   restart: always
  #   networks:
  #     - backend
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'
  #     - '--web.enable-lifecycle'

  # # Grafana dashboard
  # grafana:
  #   image: grafana/grafana:12.4.0-22081664032-ubuntu
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   env_file:
  #     - ./env/.env.grafana
  #   depends_on:
  #     - prometheus
  #   restart: always
  #   networks:
  #     - backend

  # # None Exporter for system metrics
  # node-exporter:
  #   image: prom/node-exporter:v1.10.2
  #   container_name: node-exporter
  #   ports:
  #     - "9100:9100"
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--path.rootfs=/rootfs'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   restart: always
  #   networks:
  #     - backend

  # # Postgres Exporter for database metrics
  # postgres-exporter:
  #   image: prometheuscommunity/postgres-exporter:v0.19.0
  #   container_name: postgres-exporter
  #   ports:
  #     - "9187:9187"
  #   env_file:
  #     - ./env/.env.postgres-exporter
  #   restart: always
  #   networks:
  #     - backend
  #   depends_on:
  #     - pgvector
    
networks:
  backend:
    driver: bridge

volumes:
  fastapi_data:
  # pgvector_data:
  # qdrant_data:
  # prometheus_data:
  # grafana_data:
